### ISSUE TITLE
read_imu_measurement() exception

### ISSUE THREAD

**Issue by H--o-l** [keigan-motor/pykeigan_motor#4]
Plop !

Thanks for the work on this library !
It work very well for me.

I am opening this issue just so you know, I had the following error playing with `read_imu_measurement()`:
```py
#!/usr/bin/python3

from pykeigan_motor import KMControllers
m = KMControllers.BLEController("f8:7f:03:b6:fa:42")
m.enable()
m.read_imu_measurement()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pykeigan_motor-0.1.0-py3.6.egg/pykeigan_motor/KMControllers.py", line 554, in read_imu_measurement
  File "/usr/local/lib/python3.6/site-packages/pykeigan_motor-0.1.0-py3.6.egg/pykeigan_motor/KMControllers.py", line 39, in bytes2int16_t
struct.error: unpack requires a buffer of 2 bytes
```
<br/>

You have an idea of the issue ?

(I am using Keigan Firmware v1.78, python v3.6)

**Comment by wingcloud** [comment]
Hello. Thank you for your using Keigan Motors and this library!
Sorry for your inconvenience. 
You need to call enableIMU before calling read_imu_measurement.

Please try:
```
#!/usr/bin/python3

from pykeigan_motor import KMControllers
m = KMControllers.BLEController("f8:7f:03:b6:fa:42")
m.enable()
m.enableIMU()
m.read_imu_measurement()
```

**Comment by H--o-l** [comment]
Thanks for your quick answer !
I will do it.
Closing the issue !
